// frontend/src/components/ServerMonitor.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  
  let cpuData = [];
  let memoryData = [];
  let currentStats = {
    cpu: 45,
    memory: 62,
    disk: 78,
    network: { in: 125.5, out: 89.3 }
  };
  
  let activeSessionId = null;
  let dataInterval = null;

  function getStatusColor(value) {
    if (value < 50) return '#10b981'; // green
    if (value < 80) return '#f59e0b'; // amber
    return '#ef4444'; // red
  }

  // 获取监控数据
  async function fetchMonitoringData() {
    if (!activeSessionId) return;
    
    const { GetMonitoringData } = window.wailsBindings || {};
    if (typeof GetMonitoringData !== 'function') return;

    try {
      const data = await GetMonitoringData(activeSessionId);
      if (data) {
        currentStats = {
          cpu: data.cpu || 45,
          memory: data.memory || 62,
          disk: data.disk || 78,
          network: data.network || { in: 125.5, out: 89.3 }
        };
      }
    } catch (error) {
      console.error('Failed to fetch monitoring data:', error);
    }
  }

  onMount(() => {
    // 监听活动会话变化
    const handleSessionChange = (event) => {
      activeSessionId = event.detail;
      if (activeSessionId) {
        fetchMonitoringData();
      }
    };

    window.addEventListener('active-session-changed', handleSessionChange);

    // 开始定时更新数据
    dataInterval = setInterval(fetchMonitoringData, 2000);

    return () => {
      window.removeEventListener('active-session-changed', handleSessionChange);
      clearInterval(dataInterval);
    };
  });

  onDestroy(() => {
    if (dataInterval) {
      clearInterval(dataInterval);
    }
  });
</script>

<div class="h-full flex flex-col bg-white dark:bg-gray-800 overflow-y-auto scrollbar-thin">
  <!-- 头部 -->
  <div class="p-3 border-b border-gray-200 dark:border-gray-700">
    <h3 class="text-sm font-semibold text-gray-900 dark:text-white">服务器监控</h3>
    <div class="text-xs text-gray-500 dark:text-gray-400 mt-1">
      {activeSessionId ? '实时数据获取中...' : '请先连接到服务器'}
    </div>
  </div>

  <div class="p-3 space-y-3">
    <!-- CPU 使用率 -->
    <div class="bg-gradient-to-br from-purple-50 to-blue-50 dark:from-purple-900/20 dark:to-blue-900/20 rounded-xl p-3 shadow-sm border border-purple-100 dark:border-purple-800">
      <div class="flex items-center justify-between mb-2">
        <div class="flex items-center gap-2">
          <div class="p-1.5 bg-purple-100 dark:bg-purple-900 rounded-lg">
            <svg class="w-3.5 h-3.5 text-purple-600 dark:text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 002-2h2a2 2 0 002-2z" />
            </svg>
          </div>
          <span class="text-xs font-semibold text-gray-900 dark:text-white">CPU</span>
        </div>
        <span class="text-xs font-bold px-2 py-1 rounded-lg bg-white dark:bg-gray-800" style="color: {getStatusColor(currentStats.cpu)}">
          {currentStats.cpu}%
        </span>
      </div>
      <div class="h-[80px] bg-white dark:bg-gray-800 rounded-lg flex items-center justify-center text-xs text-gray-400">
        CPU 图表待实现
      </div>
    </div>

    <!-- 内存使用率 -->
    <div class="bg-gradient-to-br from-emerald-50 to-teal-50 dark:from-emerald-900/20 dark:to-teal-900/20 rounded-xl p-3 shadow-sm border border-emerald-100 dark:border-emerald-800">
      <div class="flex items-center justify-between mb-2">
        <div class="flex items-center gap-2">
          <div class="p-1.5 bg-emerald-100 dark:bg-emerald-900 rounded-lg">
            <svg class="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 002-2h2a2 2 0 002-2z" />
            </svg>
          </div>
          <span class="text-xs font-semibold text-gray-900 dark:text-white">内存</span>
        </div>
        <span class="text-xs font-bold px-2 py-1 rounded-lg bg-white dark:bg-gray-800" style="color: {getStatusColor(currentStats.memory)}">
          {currentStats.memory}%
        </span>
      </div>
      <div class="h-[80px] bg-white dark:bg-gray-800 rounded-lg flex items-center justify-center text-xs text-gray-400">
        内存图表待实现
      </div>
    </div>

    <!-- 磁盘使用 -->
    <div class="bg-gradient-to-br from-amber-50 to-orange-50 dark:from-amber-900/20 dark:to-orange-900/20 rounded-xl p-3 shadow-sm border border-amber-100 dark:border-amber-800">
      <div class="flex items-center justify-between mb-2">
        <div class="flex items-center gap-2">
          <div class="p-1.5 bg-amber-100 dark:bg-amber-900 rounded-lg">
            <svg class="w-3.5 h-3.5 text-amber-600 dark:text-amber-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4m0 5c0 2.21-3.582 4-8 4s-8-1.79-8-4" />
            </svg>
          </div>
          <span class="text-xs font-semibold text-gray-900 dark:text-white">磁盘</span>
        </div>
        <span class="text-xs font-bold px-2 py-1 rounded-lg bg-white dark:bg-gray-800" style="color: {getStatusColor(currentStats.disk)}">
          {currentStats.disk}%
        </span>
      </div>
      <div class="w-full bg-gray-100 dark:bg-gray-700 rounded-full h-2 overflow-hidden">
        <div
          class="h-2 rounded-full transition-all duration-300"
          style="width: {currentStats.disk}%; background-color: {getStatusColor(currentStats.disk)};"
        />
      </div>
      <div class="flex justify-between mt-2 text-[10px] text-gray-600 dark:text-gray-400">
        <span>已用 156 GB</span>
        <span>总计 200 GB</span>
      </div>
    </div>

    <!-- 网络流量 -->
    <div class="bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 rounded-xl p-3 shadow-sm border border-blue-100 dark:border-blue-800">
      <div class="flex items-center gap-2 mb-3">
        <div class="p-1.5 bg-blue-100 dark:bg-blue-900 rounded-lg">
          <svg class="w-3.5 h-3.5 text-blue-600 dark:text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.111 16.404a5.5 5.5 0 017.778 0M12 20h.01m-7.08-7.071c3.904-3.905 10.236-3.905 14.141 0M1.394 9.393c5.857-5.857 15.355-5.857 21.213 0" />
          </svg>
        </div>
        <span class="text-xs font-semibold text-gray-900 dark:text-white">网络流量</span>
      </div>
      <div class="space-y-2">
        <div class="flex items-center justify-between bg-white dark:bg-gray-800 rounded-lg p-2">
          <div class="flex items-center gap-2">
            <div class="w-2 h-2 rounded-full bg-emerald-500"></div>
            <span class="text-xs text-gray-700 dark:text-gray-300 font-medium">入站</span>
          </div>
          <span class="text-xs font-mono font-bold text-gray-900 dark:text-white">
            {currentStats.network.in.toFixed(1)} MB/s
          </span>
        </div>
        <div class="flex items-center justify-between bg-white dark:bg-gray-800 rounded-lg p-2">
          <div class="flex items-center gap-2">
            <div class="w-2 h-2 rounded-full bg-rose-500"></div>
            <span class="text-xs text-gray-700 dark:text-gray-300 font-medium">出站</span>
          </div>
          <span class="text-xs font-mono font-bold text-gray-900 dark:text-white">
            {currentStats.network.out.toFixed(1)} MB/s
          </span>
        </div>
      </div>
    </div>

    <!-- 系统信息 -->
    <div class="bg-gray-50 dark:bg-gray-700 rounded-xl p-3 shadow-sm border border-gray-200 dark:border-gray-600">
      <div class="text-xs font-semibold text-gray-900 dark:text-white mb-2">系统信息</div>
      <div class="space-y-1.5 text-[10px]">
        <div class="flex justify-between py-1">
          <span class="text-gray-600 dark:text-gray-400">操作系统</span>
          <span class="text-gray-900 dark:text-white font-medium">Ubuntu 22.04 LTS</span>
        </div>
        <div class="flex justify-between py-1">
          <span class="text-gray-600 dark:text-gray-400">内核版本</span>
          <span class="text-gray-900 dark:text-white font-medium">5.15.0-91-generic</span>
        </div>
        <div class="flex justify-between py-1">
          <span class="text-gray-600 dark:text-gray-400">运行时间</span>
          <span class="text-gray-900 dark:text-white font-medium">15天 7小时 32分</span>
        </div>
        <div class="flex justify-between py-1">
          <span class="text-gray-600 dark:text-gray-400">进程数</span>
          <span class="text-gray-900 dark:text-white font-medium">187</span>
        </div>
      </div>
    </div>
  </div>
</div>

// new_frontend/src/app/components/ServerMonitor.tsx
import { useState, useEffect } from 'react';
import { LineChart, Line, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { Cpu, HardDrive, Activity, Wifi } from 'lucide-react';

export function ServerMonitor() {
  const [cpuData, setCpuData] = useState<Array<{ time: string; value: number }>>([]);
  const [memoryData, setMemoryData] = useState<Array<{ time: string; value: number }>>([]);
  const [currentStats, setCurrentStats] = useState({
    cpu: 45,
    memory: 62,
    disk: 78,
    network: { in: 125.5, out: 89.3 }
  });

  // 模拟实时数据更新
  useEffect(() => {
    // 初始化数据
    const initData = Array.from({ length: 10 }, (_, i) => ({
      time: `00:00:${i.toString().padStart(2, '0')}`,
      value: Math.floor(Math.random() * 40) + 30
    }));
    setCpuData(initData);
    setMemoryData(initData);

    const generateDataPoint = (prev: number) => {
      const change = (Math.random() - 0.5) * 10;
      const newValue = Math.max(0, Math.min(100, prev + change));
      return Math.round(newValue);
    };

    const interval = setInterval(() => {
      const now = new Date();
      const timeStr = `${now.getHours().toString().padStart(2, '0')}:${now.getMinutes().toString().padStart(2, '0')}:${now.getSeconds().toString().padStart(2, '0')}`;
      
      setCpuData(prev => {
        const newData = [...prev, { time: timeStr, value: generateDataPoint(prev[prev.length - 1]?.value || 45) }];
        return newData.slice(-20);
      });

      setMemoryData(prev => {
        const newData = [...prev, { time: timeStr, value: generateDataPoint(prev[prev.length - 1]?.value || 62) }];
        return newData.slice(-20);
      });

      setCurrentStats(prev => ({
        cpu: generateDataPoint(prev.cpu),
        memory: generateDataPoint(prev.memory),
        disk: prev.disk,
        network: {
          in: Math.max(0, prev.network.in + (Math.random() - 0.5) * 20),
          out: Math.max(0, prev.network.out + (Math.random() - 0.5) * 15)
        }
      }));
    }, 2000);

    return () => clearInterval(interval);
  }, []);

  const getStatusColor = (value: number) => {
    if (value < 50) return '#10b981';
    if (value < 80) return '#f59e0b';
    return '#ef4444';
  };

  return (
    <div className="h-full flex flex-col bg-white overflow-y-auto">
      {/* 头部 */}
      <div className="p-3 border-b border-gray-200">
        <h3 className="text-sm font-semibold text-gray-900">服务器监控</h3>
      </div>

      <div className="p-3 space-y-3">
        {/* CPU 使用率 */}
        <div className="bg-gradient-to-br from-purple-50 to-blue-50 rounded-xl p-3 shadow-sm border border-purple-100">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-2">
              <div className="p-1.5 bg-purple-100 rounded-lg">
                <Cpu className="w-3.5 h-3.5 text-purple-600" />
              </div>
              <span className="text-xs font-semibold text-gray-900">CPU</span>
            </div>
            <span className="text-xs font-bold px-2 py-1 rounded-lg bg-white" style={{ color: getStatusColor(currentStats.cpu) }}>
              {currentStats.cpu}%
            </span>
          </div>
          <div className="h-[80px]">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={cpuData}>
                <defs>
                  <linearGradient id="cpuGradient" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#9333ea" stopOpacity={0.3}/>
                    <stop offset="95%" stopColor="#9333ea" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <Area type="monotone" dataKey="value" stroke="#9333ea" fill="url(#cpuGradient)" strokeWidth={2} />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* 内存使用率 */}
        <div className="bg-gradient-to-br from-emerald-50 to-teal-50 rounded-xl p-3 shadow-sm border border-emerald-100">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-2">
              <div className="p-1.5 bg-emerald-100 rounded-lg">
                <Activity className="w-3.5 h-3.5 text-emerald-600" />
              </div>
              <span className="text-xs font-semibold text-gray-900">内存</span>
            </div>
            <span className="text-xs font-bold px-2 py-1 rounded-lg bg-white" style={{ color: getStatusColor(currentStats.memory) }}>
              {currentStats.memory}%
            </span>
          </div>
          <div className="h-[80px]">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={memoryData}>
                <defs>
                  <linearGradient id="memoryGradient" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#10b981" stopOpacity={0.3}/>
                    <stop offset="95%" stopColor="#10b981" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <Area type="monotone" dataKey="value" stroke="#10b981" fill="url(#memoryGradient)" strokeWidth={2} />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* 磁盘使用 */}
        <div className="bg-gradient-to-br from-amber-50 to-orange-50 rounded-xl p-3 shadow-sm border border-amber-100">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-2">
              <div className="p-1.5 bg-amber-100 rounded-lg">
                <HardDrive className="w-3.5 h-3.5 text-amber-600" />
              </div>
              <span className="text-xs font-semibold text-gray-900">磁盘</span>
            </div>
            <span className="text-xs font-bold px-2 py-1 rounded-lg bg-white" style={{ color: getStatusColor(currentStats.disk) }}>
              {currentStats.disk}%
            </span>
          </div>
          <div className="w-full bg-gray-100 rounded-full h-2 overflow-hidden">
            <div
              className="h-2 rounded-full transition-all duration-300"
              style={{ 
                width: `${currentStats.disk}%`,
                backgroundColor: getStatusColor(currentStats.disk)
              }}
            />
          </div>
          <div className="flex justify-between mt-2 text-[10px] text-gray-600">
            <span>已用 156 GB</span>
            <span>总计 200 GB</span>
          </div>
        </div>

        {/* 网络流量 */}
        <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-xl p-3 shadow-sm border border-blue-100">
          <div className="flex items-center gap-2 mb-3">
            <div className="p-1.5 bg-blue-100 rounded-lg">
              <Wifi className="w-3.5 h-3.5 text-blue-600" />
            </div>
            <span className="text-xs font-semibold text-gray-900">网络流量</span>
          </div>
          <div className="space-y-2">
            <div className="flex items-center justify-between bg-white rounded-lg p-2">
              <div className="flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-emerald-500" />
                <span className="text-xs text-gray-700 font-medium">入站</span>
              </div>
              <span className="text-xs font-mono font-bold text-gray-900">
                {currentStats.network.in.toFixed(1)} MB/s
              </span>
            </div>
            <div className="flex items-center justify-between bg-white rounded-lg p-2">
              <div className="flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-rose-500" />
                <span className="text-xs text-gray-700 font-medium">出站</span>
              </div>
              <span className="text-xs font-mono font-bold text-gray-900">
                {currentStats.network.out.toFixed(1)} MB/s
              </span>
            </div>
          </div>
        </div>

        {/* 系统信息 */}
        <div className="bg-gray-50 rounded-xl p-3 shadow-sm border border-gray-200">
          <div className="text-xs font-semibold text-gray-900 mb-2">系统信息</div>
          <div className="space-y-1.5 text-[10px]">
            <div className="flex justify-between py-1">
              <span className="text-gray-600">操作系统</span>
              <span className="text-gray-900 font-medium">Ubuntu 22.04 LTS</span>
            </div>
            <div className="flex justify-between py-1">
              <span className="text-gray-600">内核版本</span>
              <span className="text-gray-900 font-medium">5.15.0-91-generic</span>
            </div>
            <div className="flex justify-between py-1">
              <span className="text-gray-600">运行时间</span>
              <span className="text-gray-900 font-medium">15天 7小时 32分</span>
            </div>
            <div className="flex justify-between py-1">
              <span className="text-gray-600">进程数</span>
              <span className="text-gray-900 font-medium">187</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
